name: add-shared-parts-review
run-name: Add shared parts to the functional review firm
# We run this action when a "add-shared-parts-review-firm" label is added to the PR
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  check-add-shared-parts-review-label:
    runs-on: ubuntu-latest
    outputs:
      has_add_shared_parts_review_label: ${{ steps.haslabel.outputs.labeled-add-shared-parts-review-firm }}
    steps:
      - name: Checkout Repository - Fetch all history for all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Labeled to add shared parts
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: "add-shared-parts-review-firm"

  add-shared-parts-review:
    needs: check-add-shared-parts-review-label
    if: needs.check-add-shared-parts-review-label.outputs.has_add_shared_parts_review_label
    runs-on: ubuntu-latest
    env:
      SF_API_CLIENT_ID: "${{ secrets.SF_API_CLIENT_ID }}"
      SF_API_SECRET: "${{ secrets.SF_API_SECRET }}"
    steps:
      - name: Checkout Repository - Fetch all history for all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Add sf-toolkit package latest version
        run: |
          npm install https://github.com/silverfin/sf-toolkit.git
          VERSION=$(./node_modules/sf_toolkit/bin/cli.js -V)
          echo "CLI version: ${VERSION}"
      - name: Create Silverfin config file
        run: |
          mkdir -p $HOME/.silverfin/
          touch $HOME/.silverfin/config.json
          echo '${{ secrets.CONFIG_JSON }}' > $HOME/.silverfin/config.json
          node ./node_modules/sf_toolkit/bin/cli.js config --set-firm="${{ vars.FIRM_ID_REVIEW }}"
          node ./node_modules/sf_toolkit/bin/cli.js config --get-firm
      - name: Add shared parts
        run: |
          node ./node_modules/sf_toolkit/bin/cli.js add-shared-part --all --yes
      - name: Remove all labels
        uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Add Comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'All Shared parts were added succesfully to the "Staging firm"'
            })
      - name: Prepare CONFIG_JSON for secret
        if: always()
        run: |
          CONFIG_JSON=$(cat $HOME/.silverfin/config.json | tr -d '\n')
          echo "CONFIG_JSON=${CONFIG_JSON}" >> $GITHUB_ENV
      - name: Store CONFIG_JSON as secret
        uses: gliech/create-github-secret-action@v1
        if: always()
        with:
          name: CONFIG_JSON
          value: "${{ env.CONFIG_JSON }}"
          pa_token: ${{ secrets.REPO_ACCESS_TOKEN }}
