name: update-liquid-templates-production
run-name: Update liquid templates for deployment to partner
# We run this action when a PR is closed and merged into the main branch
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
jobs:
  update-templates-in-production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SF_API_CLIENT_ID: "${{ secrets.SF_API_CLIENT_ID }}"
      SF_API_SECRET: "${{ secrets.SF_API_SECRET }}"
    steps:
      - name: Checkout Repository - Fetch all history for all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Add sf-toolkit package latest version
        run: |
          npm install https://github.com/silverfin/sf-toolkit.git
          VERSION=$(./node_modules/sf_toolkit/bin/cli.js -V)
          echo "CLI version: ${VERSION}"
      - name: Create Silverfin config file
        run: |
          mkdir -p $HOME/.silverfin/
          touch $HOME/.silverfin/config.json
          echo '${{ secrets.CONFIG_JSON }}' > $HOME/.silverfin/config.json
          node ./node_modules/sf_toolkit/bin/cli.js config --set-firm="${{ vars.FIRM_ID_PRODUCTION }}"
          node ./node_modules/sf_toolkit/bin/cli.js config --get-firm
      - name: Get changed liquid files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: false
          dir_names: true
          files: |
            **/*.liquid
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Update liquid templates
        run: |
          declare -a ERRORS
          FIRM_ID=${{ vars.FIRM_ID_PRODUCTION }}

          for CURRENT_DIR in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Checking directory: ${CURRENT_DIR}"
            while [[ "${CURRENT_DIR}" != "." ]]; do
              if [[ -e "${CURRENT_DIR}/config.json" ]]; then
                echo "Found config.json in ${CURRENT_DIR}. Handle: ${HANDLE}"

                HANDLE=$(cat ${CURRENT_DIR}/config.json | jq -r ".handle // .name")
                FIRM_IDS=$(cat ${CURRENT_DIR}/config.json | jq -r ".id" | jq "keys_unsorted" | jq -r ".[]")

                # Set template type
                TEMPLATE_TYPE=""
                FLAG=""
                if [[ "${CURRENT_DIR}" == *reconciliation_texts* ]]; then
                  TEMPLATE_TYPE="reconciliation"
                  FLAG="--handle"
                elif [[ "${CURRENT_DIR}" == *shared_parts* ]]; then
                  TEMPLATE_TYPE="shared-part"
                  FLAG="--shared-part"
                fi
                # TODO: handle missing type

                # Do we already have the id of this template ?
                TEMPLATE_ID_PRESENT=false
                if  [[ "${FIRM_IDS[*]}" =~ "${FIRM_ID}" ]]; then
                  TEMPLATE_ID_PRESENT=true
                fi
                echo "Is firm id present in the config.json of template ${HANDLE}?: ${TEMPLATE_ID_PRESENT}"

                # If we don't have the ID, try to get it from the firm
                if [[ "$TEMPLATE_ID_PRESENT" == 'false' ]]; then
                  echo "Try to fetch the ID from firm id: ${FIRM_ID}"
                  # get-reconciliation-id or get-shared-part-id
                  OUTPUT_ID=$(node ./node_modules/sf_toolkit/bin/cli.js get-"${TEMPLATE_TYPE}"-id "${FLAG}"="${HANDLE}" --yes)
                
                  if [[ "$OUTPUT_ID" =~ "ID updated" ]]; then
                    echo "Template: ${HANDLE} ID fetched from firm ${FIRM_ID}"
                    TEMPLATE_ID_PRESENT=true
                  elif [[ "$OUTPUT_ID" =~ "not found" ]]; then
                    echo "Template: ${HANDLE} ID not found in firm ${FIRM_ID}"
                  else
                    echo "Command to fetch the ID failed"
                  fi
                fi

                # Update or created. Based on the presence of a template ID
                if  [[ "$TEMPLATE_ID_PRESENT" == 'true' ]]; then
                  echo "Updating ${HANDLE}"
                  # update-reconciliation or update-shared-part
                  OUTPUT=$(node ./node_modules/sf_toolkit/bin/cli.js update-"${TEMPLATE_TYPE}" "${FLAG}"="${HANDLE}" --yes)
                  OPERATION_TYPE="update"
                else
                  echo "Creating ${HANDLE}"
                  # create-reconciliation or create-shared-part
                  OUTPUT=$(node ./node_modules/sf_toolkit/bin/cli.js create-"${TEMPLATE_TYPE}" "${FLAG}"="${HANDLE}")
                  OPERATION_TYPE="create"
                fi

                if [[ "$OUTPUT" =~ "201" ]]; then
                  echo "Template ${HANDLE}: succesfully ${OPERATION_TYPE}d in firm ${FIRM_ID}" 
                else
                  echo "Template ${HANDLE}: failed to ${OPERATION_TYPE} in firm ${FIRM_ID}"
                  ERRORS+=("${OUTPUT}")
                fi

                break
              else
                echo "Config file not found in directory: ${CURRENT_DIR}"
                CURRENT_DIR="$(dirname "${CURRENT_DIR}")"
              fi
            done
          done

          # CHECK ERRORS PRESENT
          if [ ${#ERRORS[@]} -eq 0 ]; then
              echo "All templates have been updated and/or created"
          else
              echo "Errors: ${ERRORS[@]}"
              exit 1
          fi
      - name: Remove all labels
        uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Add deploy to partner label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["3-deploy-to-partner"]
            })
      - name: Prepare CONFIG_JSON for secret
        run: |
          CONFIG_JSON=$(cat $HOME/.silverfin/config.json | tr -d '\n')
          echo "CONFIG_JSON=${CONFIG_JSON}" >> $GITHUB_ENV
        if: always()
      - name: Store CONFIG_JSON as secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: CONFIG_JSON
          value: "${{ env.CONFIG_JSON }}"
          pa_token: ${{ secrets.REPO_ACCESS_TOKEN }}
        if: always()
